---
- name: Include CIS common 
  include_tasks: common.yml

# Files & ownership controls (1.1.*)
- name: Include master files permissions tasks
  include_tasks: files_permissions.yml

# API server flags & apiserver config checks (1.2.*)
- name: Include API server flags tasks
  include_tasks: api_server_flags.yml
  
# Controller manager flags & config checks (1.3.*)
- name: Controller manager flags tasks
  include_tasks: controller_manager_flags.yml

# Scheduler flags & config checks (1.4.*)
- name: Scheduler flags tasks
  include_tasks: scheduler_flags.yml
