# paths (override in group_vars if needed)
kube_cis_etcd_manifest: "{{ k8s_manifests_dir }}/etcd.yaml"
kube_cis_etcd_cert_path: "/etc/kubernetes/pki/etcd"
kube_cis_etcd_data_dir: "/var/lib/etcd"
k8s_manifests_dir: /etc/kubernetes/manifests

# kubespray enable set true, disable set false
kubespray: false
