name: ğŸš€ Build, Push & Attach Source

on:
  # Action Workflow when new Release PUBLISH
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # with 'write' push Image  GHCR
      
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4
      # ==========================================================
      # ğŸ³ Setup and Metadata Docker
      # ==========================================================

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: ğŸ” Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: ğŸ·ï¸ Prepare metadata (Image tagging)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} 
          tags: |
            type=semver,pattern={{version}} 
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          tags-output: true

      # ==========================================================
      # ğŸ³ Build and Push Image
      # ==========================================================

      - name: ğŸ“¦ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # ==========================================================
      # ğŸ›¡ï¸ TRIVY SCAN (High Severity +)
      # ==========================================================

      - name: ğŸ›¡ï¸ Run Trivy Vulnerability Scan (High+)
        uses: aquasecurity/trivy-action@master
        id: trivy_scan
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          severity: 'HIGH,CRITICAL'
          format: 'table'
          ignore-unfixed: true
          scanners: vuln
          vuln-type: os,library
          # Format sarif for GitHub Security Alert
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: â¬†ï¸ Upload Trivy Scan Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'          

      - name: âœ… Report Success
        run: echo "Image successfully pushed to GHCR and Source Archive attached to Release."
